# Generated by Django 6.0.3 on 2026-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('tool', 'Tool'), ('consumable', 'Consumable'), ('valuable', 'Valuable')], default='', max_length=50)),
                ('rarity', models.CharField(default='', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('effect', models.TextField(blank=True, default='', null=True)),
                ('image_path', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('health', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('loot', models.ManyToManyField(blank=True, default='', to='Info.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=100)),
                ('inventory', models.ManyToManyField(blank=True, to='Info.item')),
            ],
        ),
    ]
