# Generated by Django 6.0.3 on 2026-03-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.TextField(default=''),
        ),
    ]
