# Generated by Django 6.0.3 on 2026-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='loot',
        ),
        migrations.AddField(
            model_name='monster',
            name='danger',
            field=models.IntegerField(default=0),
        ),
    ]
