# Generated by Django 6.0.3 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_remove_monster_loot_monster_danger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('tool', 'Tool'), ('upgrade', 'Upgrade'), ('consumable', 'Consumable'), ('valuable', 'Valuable')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.CharField(default=''),
        ),
    ]
