# Generated by Django 6.0.4 on 2026-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_alter_item_type_alter_monster_damage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(default=0),
        ),
    ]
