# Generated by Django 6.0.4 on 2026-04-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0005_remove_item_rarity_alter_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(default=''),
        ),
    ]
