# Generated by Django 6.0.3 on 2026-04-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_remove_player_health_remove_player_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='')),
                ('value', models.CharField(default='')),
                ('place', models.CharField(default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
