# Generated by Django 6.0.3 on 2026-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0007_valuables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valuables',
            new_name='Valuable',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('tool', 'Tool'), ('upgrade', 'Upgrade'), ('consumable', 'Consumable')], default='', max_length=50),
        ),
    ]
