# Generated by Django 6.0.3 on 2026-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0008_rename_valuables_valuable_alter_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelore',
            options={'verbose_name_plural': 'Game Lores'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('tool', 'Tool'), ('upgrade', 'Upgrade'), ('consumable', 'Consumable')], default='tool', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='valuable',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='valuable',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valuable',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
