# Generated by Django 6.0.3 on 2026-04-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0009_alter_gamelore_options_remove_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuable',
            name='size',
            field=models.CharField(default=0),
        ),
    ]
