# Generated by Django 6.0.3 on 2026-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0010_alter_valuable_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuable',
            name='value',
            field=models.CharField(default=0),
        ),
    ]
