# Generated by Django 6.0.3 on 2026-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0011_alter_valuable_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
