# Generated by Django 6.0.3 on 2026-04-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0012_player_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(default=''),
        ),
    ]
