# Generated by Django 6.0.3 on 2026-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0013_alter_item_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='damage',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='danger',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.CharField(default=0),
        ),
    ]
